Repository team-haribo/GOMS-iOS-Admin, pull requests merged in 2023-09, with the labels that each got.

#87 🔀 :: 86 Add BlackList API
  Project/GOMS-iOS-Admin/Sources/Data/Services/StudentCouncil/StudentCouncilServices.swift
Labels: 📬 API

#89 🔀 :: 가독성 추가
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/View/IntroViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Splash/SplashViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/View/HomeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/SearchModal/View/SearchModalViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/StudentInfo/StudentInfoCollectionViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/TabBar/GOMSAdminTabBar.swift
Labels: 🔨 Refactor

#91 🔀 :: Change File Structure
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Auth/Intro/Reactor/IntroReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Auth/Intro/View/IntroViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Auth/LoginWithNumber/Reactor/LoginWithNumberReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Auth/Splash/SplashViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/EditModal/Reactor/EditModalReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/EditModal/View/EditModalViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Home/Cell/HomeCollectionViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Home/Reactor/HomeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Home/View/HomeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Outing/Reactor/OutingReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Outing/View/OutingViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Profile/Cell/ProfileTableViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Profile/Reactor/ProfileReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Profile/View/ProfileViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/QRCode/Reactor/QRCodeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/QRCode/View/QRCodeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/SearchModal/Reator/SearchModalReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/SearchModal/View/CustomSegmentedControl.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/SearchModal/View/SearchModalViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/StudentInfo/Reactor/StudentInfoReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/StudentInfo/StudentInfoCollectionViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/StudentInfo/View/StudentInfoViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/TabBar/GOMSAdminTabBar.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/DesignSystem/LoginWithNumberTextField.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/GOMSAdminRefreshToken.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/GOMSAdminShadow.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/GOMSAdminTextField.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/GOMSAdminToken.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/GOMSImageView.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/Rx/LoginWithNumber+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/Rx/Profile+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/Rx/QRCode+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/Rx/UILabel+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Utils/Extension/UINavigationBar.swift
Labels: 🔨 Refactor

#93 🔀 :: Update README.md
  README.md
Labels: 📃 Docs

#92 🔀 :: outinginfo view publishing
  Project/GOMS-iOS-Admin/Sources/Data/Request/StudenCouncil/EditAuthority/editAuthorityRequest.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/Cell/OutingCollecionViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Outing/Reactor/OutingReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Outing/View/OutingViewController.swift
Labels: ✨ Feature, 🙋‍♂️ Question

#97 🔀 :: 75 student info binding
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Step/GOMSAdminStep.swift
  Project/GOMS-iOS-Admin/Sources/Data/Request/StudenCouncil/EditAuthority/editAuthorityRequest.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/EditModal/Reactor/EditModalReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/EditModal/View/EditModalViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/SearchModal/View/CustomSegmentedControl.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/StudentInfo/Reactor/StudentInfoReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/StudentInfo/View/StudentInfoViewController.swift
Labels: ✨ Feature

#100 🔀 :: 99 search api
  Project/GOMS-iOS-Admin/Sources/Data/Model/StudentCouncil/SearchStudent/SearchModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/StudentCouncil/StudentCouncilServices.swift
Labels: 📬 API

#101 🔀 :: 94 View OutingInfo Cell
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Outing/Cell/OutingCollecionViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Outing/Reactor/OutingReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/Outing/View/OutingViewController.swift
Labels: ✨ Feature

#103 98 search binding
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Step/GOMSAdminStep.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/SearchModal/Reator/SearchModalReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/SearchModal/View/SearchModalViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/StudentInfo/Reactor/StudentInfoReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/StudentInfo/View/StudentInfoViewController.swift
Labels: ✨ Feature

#105 🔀 :: 104 blacklist delete binding
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/EditModal/Reactor/EditModalReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Scene/Main/EditModal/View/EditModalViewController.swift
Labels: ✨ Feature
