Repository team-haribo/GOMS-iOS-Admin, pull requests merged in 2023-08, with the labels that each got.

#4 🔀 :: 3 rxflow setting
  Project/GOMS-iOS-Admin/Sources/Application/AppFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/OutingFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/QRCodeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/TabBar/TabBarFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Step/GOMSAdminStep.swift
  Project/GOMS-iOS-Admin/Sources/Application/SceneDelegate.swift
Labels: ✨ Feature

#6 🔀 :: Add ReatorKit
  Project/GOMS-iOS-Admin/Project.swift
Labels: ✨ Feature

#9 🔀 :: Create pull_request_template.md
  .github/pull_request_template.md
Labels: ✨ Feature

#8 🔀 :: 7 publishing intro view
  .package.resolved
  Project/GOMS-iOS-Admin/Project.swift
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Color/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Color/MainColor.colorset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Color/background.colorset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/IntroLogo.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/IntroLogo.imageset/IntroLogo.svg
  Project/GOMS-iOS-Admin/Resources/Font/Fraunces-Black.ttf
  Project/GOMS-iOS-Admin/Resources/Font/SF-Pro-Text-Bold.otf
  Project/GOMS-iOS-Admin/Resources/Font/SF-Pro-Text-Medium.otf
  Project/GOMS-iOS-Admin/Resources/Font/SF-Pro-Text-Regular.otf
  Project/GOMS-iOS-Admin/Resources/Font/SF-Pro-Text-Semibold.otf
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/View/IntroViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/ViewModel/IntroViewModel.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Base/View/BaseViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Base/ViewModel/BaseViewModel.swift
Labels: ✨ Feature

#11 🔀 :: 10 tabbarflow setting
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Color/SubColor.colorset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/selectedAdminHome.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/selectedAdminHome.imageset/selectHome.svg
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/selectedAdminOuting.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/selectedAdminOuting.imageset/selectedAdminOuting.svg
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/selectedAdminQRCode.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/selectedAdminQRCode.imageset/selectedAdminQRCode.svg
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/unselectedAdminHome.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/unselectedAdminHome.imageset/unselectedHome.svg
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/unselectedAdminOuting.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/unselectedAdminOuting.imageset/unselectedAdminOuting.svg
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/unselectedAdminQRCode.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/TabBar/unselectedAdminQRCode.imageset/unselectedAdminQRCode.svg
  Project/GOMS-iOS-Admin/Sources/Application/AppFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/OutingFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/QRCodeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/TabBar/TabBarFlow.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/View/IntroViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Home/View/HomeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Home/ViewModel/HomeViewModel.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Outing/View/OutingViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Outing/ViewModel/OutingViewModel.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/QRCode/View/QRCodeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/QRCode/ViewModel/QRCodeViewModel.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/TabBar/GOMSAdminTabBar.swift
Labels: ✨ Feature

#15 🔀 :: 14 apply intro viewmodel reactorkit
  .package 2.resolved
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/OutingFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/QRCodeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Extension/GOMSAdminShadow.swift
  Project/GOMS-iOS-Admin/Sources/Extension/UINavigationBar.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/Reactor/IntroReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/View/IntroViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/ViewModel/IntroViewModel.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Base/View/BaseViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Base/ViewModel/BaseViewModel.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Home/Reactor/HomeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Home/View/HomeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Home/ViewModel/HomeViewModel.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Outing/Reactor/OutingReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Outing/View/OutingViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Outing/ViewModel/OutingViewModel.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/QRCode/Reactor/QRCodeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/QRCode/View/QRCodeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/QRCode/ViewModel/QRCodeViewModel.swift
Labels: 🔨 Refactor

#17 🔀 :: 16 loginWithNumber view publishing
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  Project/GOMS-iOS-Admin/Sources/DesignSystem/LoginWithNumberTextField.swift
  Project/GOMS-iOS-Admin/Sources/Extension/GOMSAdminTextField.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/Reactor/LoginWithNumberReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/Cell/HomeCollectionViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/Reactor/HomeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/View/HomeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/Reactor/OutingReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Outing/View/OutingViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/QRCode/Reactor/QRCodeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/QRCode/View/QRCodeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/TabBar/GOMSAdminTabBar.swift
Labels: ✨ Feature

#19 🔀 :: Add LaunchScreen
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Intro/SplashLogo.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Intro/SplashLogo.imageset/GOMS.svg
  Project/GOMS-iOS-Admin/Resources/LaunchScreen.storyboard
Labels: ✨ Feature

#21 🔀 :: 20 add splash view
  .package.resolved
  Project/GOMS-iOS-Admin/Project.swift
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Intro/SplashBearLogo.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Intro/SplashBearLogo.imageset/곰탱이.svg
  Project/GOMS-iOS-Admin/Sources/Application/AppFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Step/GOMSAdminStep.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Splash/SplashViewController.swift
Labels: ✨ Feature

#23 🔀 :: Splash Logo Image Bug
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Intro/SplashBearLogo.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Intro/SplashBearLogo.imageset/곰탱이 1.svg
Labels: 🐞 BugFix

#25 🔀 :: 24 sign in api
  Project/GOMS-iOS-Admin/Sources/Data/General/BaseURL.swift
  Project/GOMS-iOS-Admin/Sources/Data/Model/Auth/SignIn/SignInModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Request/Auth/SignInRequest.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/Auth/AuthServices.swift
Labels: 📬 API

#28 🔀 :: Add GOMS Admin Keychain
  Project/GOMS-iOS-Admin/Sources/Extension/GOMSAdminToken.swift
Labels: ✨ Feature

#29 🔀 :: 26 signin binding
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/Reactor/IntroReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/View/IntroViewController.swift
Labels: ✨ Feature

#31 🔀 :: 학생 계정 예외처리
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/Reactor/IntroReactor.swift
Labels: ✨ Feature

#33 🔀 :: QRCode View Publishing
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/QRCode/View/QRCodeViewController.swift
Labels: ✨ Feature

#35 🔀 :: 34 Create QRCode API
  Project/GOMS-iOS-Admin/Sources/Data/Model/StudentCouncil/CreateQRCode/CreateQRCodeModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/StudentCouncil/StudentCouncilServices.swift
Labels: 📬 API

#40 🔀 :: Add AppIcon
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/AppIcon.appiconset/Group 17704.png
Labels: ✨ Feature

#42 🔀 :: 41 app name setting
  Project/GOMS-iOS-Admin/Project.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/TabBar/TabBarFlow.swift
  Project/GOMS-iOS-Admin/Sources/DesignSystem/LoginWithNumberTextField.swift
  Project/GOMS-iOS-Admin/Sources/Extension/UINavigationBar.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/View/IntroViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Base/View/BaseViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/Cell/HomeCollectionViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/View/HomeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Profile/Cell/ProfileTableViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Profile/View/ProfileViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/QRCode/View/QRCodeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/TabBar/GOMSAdminTabBar.swift
Labels: 🔨 Refactor

#44 🔀 :: 43 Refresh Token API
  Project/GOMS-iOS-Admin/Sources/Data/Model/Auth/RefreshToken/RefreshTokenModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/Auth/AuthServices.swift
Labels: 📬 API

#47 🔀 :: Add Auto Login
  Project/GOMS-iOS-Admin/Sources/Extension/GOMSAdminRefreshToken.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Splash/SplashViewController.swift
Labels: ✨ Feature

#50 🔀 :: 49 home view navigation logic
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/TabBar/TabBarFlow.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/Reactor/HomeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/View/HomeViewController.swift
Labels: ✨ Feature

#54 🔀 :: 53 outing count api
  Project/GOMS-iOS-Admin/Sources/Data/Model/Outing/OutingCount/OutingCountModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/Outing/OutingServices.swift
Labels: 📬 API

#52 🔀 :: 51 Fetch Profile API
  Project/GOMS-iOS-Admin/Sources/Data/Model/Account/Profile/FetchProfileModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/Account/AccountServices.swift
Labels: 📬 API

#56 🔀 :: 55 fetch late rank api
  Project/GOMS-iOS-Admin/Sources/Data/Model/Late/FetchLateRank/FetchLateRankModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/Late/LateServices.swift
Labels: 📬 API

#59 🔀 :: 58 outing count binding
  Project/GOMS-iOS-Admin/Sources/Extension/UILabel+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/Reactor/HomeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/View/HomeViewController.swift
Labels: ✨ Feature

#61 🔀 :: 60 late rank binding
  Project/GOMS-iOS-Admin/Sources/Data/General/BaseURL.swift
  Project/GOMS-iOS-Admin/Sources/Extension/GOMSAdminRefreshToken.swift
  Project/GOMS-iOS-Admin/Sources/Extension/UILabel+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/Reactor/IntroReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/Reactor/HomeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/View/HomeViewController.swift
Labels: ✨ Feature

#63 🔀 :: 62 profile binding
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Profile/logoutIcon.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/Profile/logoutIcon.imageset/􁏜2.svg
  Project/GOMS-iOS-Admin/Sources/Extension/Rx/Profile+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Extension/Rx/QRCode+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Extension/Rx/UILabel+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Profile/Cell/ProfileTableViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Profile/Reactor/ProfileReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Profile/View/ProfileViewController.swift
Labels: ✨ Feature

#65 64 Login With Number API
  Project/GOMS-iOS-Admin/Sources/Data/Model/Auth/EmailVerify/EmailVerifyModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Request/Auth/SendEmailRequest.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/Auth/AuthServices.swift
Labels: 📬 API

#67 🔀 :: 66 send email binding
  Project/GOMS-iOS-Admin/Sources/Data/Request/Auth/SendEmailRequest.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/Auth/AuthServices.swift
  Project/GOMS-iOS-Admin/Sources/Extension/Rx/LoginWithNumber+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/Reactor/LoginWithNumberReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
Labels: ✨ Feature

#69 🔀 :: 68 add logout
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/Intro/View/IntroViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Profile/Reactor/ProfileReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Profile/View/ProfileViewController.swift
Labels: ✨ Feature

#71 🔀 :: 70 loginwithnumber view error
  Project/GOMS-iOS-Admin/Sources/Data/Request/Auth/SendEmailRequest.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/Auth/AuthServices.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/Reactor/LoginWithNumberReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
Labels: 🐞 BugFix

#72 🔀 :: 45 student info view publishing
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/Reset.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/Reset.imageset/Image.png
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/Search.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/Search.imageset/Image.png
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/editIcon.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/editIcon.imageset/Image.png
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/noResultImage.imageset/Contents.json
  Project/GOMS-iOS-Admin/Resources/Assets.xcassets/Image/StudentInfo/noResultImage.imageset/Image.png
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Step/GOMSAdminStep.swift
  Project/GOMS-iOS-Admin/Sources/Data/Model/StudentCouncil/StudentList/StudentListModel.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/StudentCouncil/StudentCouncilServices.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/EditModal/Reactor/EditModalReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/EditModal/View/EditModalViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/Reactor/HomeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/View/HomeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/SearchModal/Reator/SearchModalReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/SearchModal/View/CustomSegmentedControl.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/SearchModal/View/SearchModalViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/StudentInfo/Reactor/StudentInfoReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/StudentInfo/StudentInfoCollectionViewCell.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/StudentInfo/View/StudentInfoViewController.swift
Labels: ✨ Feature

#74 🔀 :: 73 studentinfo view refactoring
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  Project/GOMS-iOS-Admin/Sources/Application/Flow/Step/GOMSAdminStep.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/Reactor/HomeReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/Home/View/HomeViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/SearchModal/View/SearchModalViewController.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/StudentInfo/View/StudentInfoViewController.swift
Labels: 🔨 Refactor

#78 🔀 :: 77 email verify binding
  Project/GOMS-iOS-Admin/Sources/Extension/Rx/LoginWithNumber+Rx.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/Reactor/LoginWithNumberReactor.swift
  Project/GOMS-iOS-Admin/Sources/Presentation/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
Labels: ✨ Feature

#80 🔀 :: Profile API Change
  Project/GOMS-iOS-Admin/Sources/Data/Model/Account/Profile/FetchProfileModel.swift
Labels: 📬 API

#82 🔀 :: 81 user number formatting
  Project/GOMS-iOS-Admin/Sources/Presentation/Main/StudentInfo/View/StudentInfoViewController.swift
Labels: 🔨 Refactor

#83 🔀 :: Update README.md
  README.md
Labels: 📃 Docs

#85 🔀 :: 84 authority api
  Project/GOMS-iOS-Admin/Sources/Data/Request/StudentCouncil/EditAuthority/EditAuthorityRequest.swift
  Project/GOMS-iOS-Admin/Sources/Data/Services/StudentCouncil/StudentCouncilServices.swift
Labels: 📬 API
